### ISSUE TITLE
strip off extra .git if repo url ends with it

### ISSUE THREAD

**Issue by johnjg12** [pnkvalavala/repochat#1]
the clone_repo function url always adds a ".git" to the URL

`command = f'git clone {git_url}.git {repo_path} && rm -rf {repo_path}/.git'`

but if you paste the repo URL for HTTPS from GitHub from the code button it always has this. i.e. `https://github.com/pnkvalavala/repochat.git`
then the command that ends up getting run is 
`git clone https://github.com/pnkvalavala/repochat.git.git ./cloned_repo && rm -rf ./cloned_repo/.git`
which then it assumes it's a private repo since it is a 404 not found then you are prompted for your password on the CLI (not frontend). and it never completes.

I think simply adding an rstrip(".git") would be an elegant solution so people can paste the path in front end with or without .git and it will work either way:

```python
git_url = git_url.rstrip(".git")
command = f'git clone {git_url}.git {repo_path} && rm -rf {repo_path}/.git'
```

**Comment by pnkvalavala** [comment]
Issue has been resolved. The changes have been made in commit [remove .git in the git_url](https://github.com/pnkvalavala/repochat/commit/88c40bffb01639ff889a3249a5f273b3ef059d97)

I noticed that using `rstrip(".git")` would inadvertently remove characters from the end of the URL, which could lead to issues. Therefore, I opted for using `replace` to specifically remove '.git' and ensure that the rest of the URL remains intact. 

Thank you for bringing this to my attention. If you encounter any further issues or have additional feedback, please don't hesitate to open a new issue. I appreciate your feedback and contributions!
